name: Check for deployment keyword

on:
  pull_request:
    types: [closed]

jobs:
  check-for-deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEYWORD: "<deploy>"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: get deployment environment
        if: github.event.pull_request.merged == true
        run: |
          function get_environment() {
            local environment=$(echo "$1" | grep -oP "(?<=${{ env.DEPLOY_KEYWORD }}:)[^ ]+")
            if [[ -z "$environment" ]]; then
              echo "No environment specified."
            else
              echo "$environment"
            fi
          }

          if [[ "${{ github.event.pull_request.title }}" == *"${{ env.DEPLOY_KEYWORD }}:"* ]]; then
            environment=$(get_environment "${{ github.event.pull_request.title }}")
          elif [[ "${{ github.event.pull_request.body }}" == *"${{ env.DEPLOY_KEYWORD }}:"* ]]; then
            environment=$(get_environment "${{ github.event.pull_request.body }}")
          else
            echo "PR was merged but does not contain ${{ env.DEPLOY_KEYWORD }}."
          fi

          if [[ -n "$environment" ]]; then
            echo "Environment: $environment"
            # Trigger job here
          fi
