name: Check for @deploy

on:
  pull_request:
    types: [closed]

jobs:
  check-for-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"&deploy:"* ]]; then
            echo "PR was merged and contains @deploy!"
            environment=$(echo "${{ github.event.pull_request.title }}" | grep -oP '(?<=&deploy:)[^ ]+')
            echo "Environment of choice is $environment"
          elif [[ "${{ github.event.pull_request.body }}" == *"&deploy:"* ]]; then
            echo "PR was merged and contains &deploy!"
            environment=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=&deploy:)[^ ]+')
            if [[ -z "$environment" ]]; then
              echo "No environment specified."
            else
              echo "Environment of choice is $environment"
              # Trigger job here
            fi
          else
            echo "PR was merged but does not contain @deploy."
          fi
          
