name: Deploy to development by detecting changes in directory

env:
  ENVIRONMENT: development

on:
  pull_request:
    types: [closed]
    branches: 
      - main
    paths:
      - "development/**"

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deployment-workflow.yml
    with:
      environment: env.ENVIRONMENT
      runs_on: ubuntu-latest
