name: Deploy to production by detecting changes in directory

env:
  ENVIRONMENT: production

on:
  pull_request:
    types: [closed]
    branches: 
      - main
    paths:
      - "production/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/reusable-deployment-workflow.yml
    with:
      environment: env.ENVIRONMENT
