name: Deploy to production by detecting changes in directory

env:
  ENVIRONMENT: production

on:
  pull_request:
    types: [closed]
    branches: 
      - main
    paths:
      - "production/**"

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/checkout
      - name: deploy
        if: env.ENVIRONMENT
        uses: ./.github/actions/reusable-deployment-workflow.yml
        with:
          environment: env.ENVIRONMENT
