name: Deploy to staging by detecting changes in directory

env:
  ENVIRONMENT: staging

on:
  pull_request:
    types: [closed]
    branches: 
      - main
    paths:
      - "staging/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/reusable-deployment-workflow.yml
    with:
      environment: env.ENVIRONMENT
