name: reusable workflow for deployment to environment of choice

on:
  workflow_call:
    inputs:
      environment:
        description: name of deployment environment
        required: true
        type: string
      runs_on:
        description: name of runner that the workflow will run on
        required: true
        type: string

jobs:
  detect_changes:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set profile
        if: ${{ inputs.environment }}
        run: echo "AWS_PROFILE=${{ inputs.environment }}" >> $GITHUB_ENV
      
      - name: check profile
        if: env.AWS_PROFILE
        run: echo "aws s3 ls --profile=${{ env.AWS_PROFILE }}"
      
      - name: init terraform
        if: ${{ inputs.environment }}
        run: echo "terraform init"

      - name: run terraform
        if: ${{ inputs.environment }}
        run: echo "terraform apply -auto-approve"
