name: Manual deployment using workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment which the application will be deployed on'
        required: true
        default: 'development'

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deployment-workflow.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      runs_on: "ubuntu-latest"
